FROM tensorflow/tensorflow:latest-py3-jupyter
MAINTAINER SockyJam <sockyjam@126.com>

RUN set -x; \
pip3 install opencv-python

RUN apt-get update;\
    apt-get install  -y python-qt4

RUN pip3 install pillow



